version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Yarn Install
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test --verbose

workflows:
  version: 2
  test-flow:
    jobs:
      - test
