version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Setup environment
          command: docker-compose up -d --build
      - run:
          name: Lint
          command: docker-compose run super-api yarn lint
      - run:
          name: Test
          command: docker-compose run -e CI=true super-api yarn test --verbose

workflows:
  version: 2
  test-flow:
    jobs:
      - test
